try{
let letTry=undefined
console.log(undefined[0]);}
catch(exception ){
    console.log("this is catch ");
    // console.log(exception);
}
finally{
    console.log("it is the block which is always run ");
}